### PR TITLE
added support of several gunicorn CLI configs

### PR DESCRIPTION
**Pull request by cyppan**
I propose to add support for gevent + eventlet worker classes. I've added also some overridable CLI params for gunicorn.

### CODE REVIEW

**Comment by devoto13** [comment]
I agree that adding more flags with default values is good idea. 

However installing additional libraries into base container sounds like overkill for me. This container is intended to be used as a [base image](https://github.com/devoto13/docker-gunicorn#usage) for building containers for specific applications.

With additional flags merged you can install `gevent`, `eventlet` as a part of your own application:

```
FROM devoto13/gunicorn
MAINTAINER Yaroslav Admin <devoto13@gmail.com>

RUN pip install gevent eventlet
ADD . /root/app
```

and specify workers by setting `$WORKER_CLASS` environment variable. Is this solution fine for you?

**Comment by cyppan** [comment]
Yes I agree that additional dependencies should be done downstream. 
This solution is fine, I modify my PR then!

**Comment by devoto13** [comment]
Merged. 
Thank you for contribution.

**Comment by cyppan** [comment]
Nice, thanks for your image ;)

2015-04-27 16:18 GMT+02:00 Yaroslav Admin <notifications@github.com>:

> Merged.
> Thank you for contribution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devoto13/docker-gunicorn/pull/3#issuecomment-96671472>
> .
>



-- 
Cyprien Pannier.

**Pull request merged**
